const passages=[
{id:"garden",level:1,zone:"Vocabulary Village",icon:"🌱",title:"The Rise of Urban Gardens",intro:"How small green spaces are changing city life",paras:["In recent years, urban gardens have become increasingly popular. These gardens allow residents to grow vegetables in small spaces, including rooftops and unused plots of land. Researchers suggest that community gardens may improve access to fresh produce and strengthen relationships between neighbours.","Beyond providing food, urban gardens can make neighbourhoods more attractive and help reduce the amount of heat absorbed by concrete surfaces. Some schools have introduced gardens to teach children about ecosystems, nutrition, and responsibility. Participants often report that gardening gives them a welcome break from busy city routines.","However, these projects are not always easy to maintain. Reliable water supplies, suitable soil, and continued participation from local residents are important. In some cities, gardens occupy land that may later be needed for housing or commercial development."],qs:[
{type:"Multiple choice",q:"What is one benefit of community gardens?",opts:["They guarantee lower food prices.","They can help neighbours build stronger relationships.","They remove the need for housing.","They require no maintenance."],a:1,why:"The first paragraph says community gardens may strengthen relationships between neighbours.",ev:"“strengthen relationships between neighbours.”"},
{type:"True / False / Not Given",q:"All urban gardens are located on rooftops.",opts:["TRUE","FALSE","NOT GIVEN"],a:1,why:"The passage mentions rooftops and unused plots of land, so not all gardens are on rooftops.",ev:"“including rooftops and unused plots of land.”"},
{type:"Short answer",q:"Name one resource needed to maintain urban gardens.",a:["reliable water supplies","water","suitable soil"],why:"The passage lists reliable water supplies and suitable soil as important resources.",ev:"“Reliable water supplies, suitable soil...”"}]},
{id:"library",level:1,zone:"Vocabulary Village",icon:"📚",title:"Libraries in a Digital Age",intro:"Why public libraries continue to evolve",paras:["Public libraries have changed considerably since widespread internet access. Although many people now read on screens, libraries remain useful places to study, meet others, and access reliable information. Many branches lend e-books and audiobooks as well as printed materials.","Libraries also offer services not strictly related to reading. Some provide computer access, language classes, employment workshops, or help with online forms. These services can be valuable for people who do not have suitable technology at home.","Despite these developments, libraries face financial pressure. Buildings need maintenance, staff require training, and digital collections can involve licensing fees. Library managers must distribute limited budgets while responding to changing community needs."],qs:[
{type:"Multiple choice",q:"What does the passage suggest about modern libraries?",opts:["They only lend printed books.","They have stopped offering study spaces.","They offer services beyond lending books.","They no longer need trained staff."],a:2,why:"The second paragraph describes computer access, classes, workshops and online-form help.",ev:"“services not strictly related to reading.”"},
{type:"True / False / Not Given",q:"Every public library offers employment workshops.",opts:["TRUE","FALSE","NOT GIVEN"],a:2,why:"The passage says some branches offer workshops. It does not say every library does.",ev:"“Some provide ... employment workshops...”"},
{type:"Sentence completion",q:"Libraries may pay licensing fees for digital ______.",a:["collections","digital collections"],why:"The final paragraph mentions licensing fees for digital collections.",ev:"“digital collections can involve licensing fees.”"}]},
{id:"sleep",level:2,zone:"Scanning Station",icon:"🔎",title:"The Science of Sleep",intro:"What researchers know about rest and learning",paras:["Sleep is an active biological process rather than simply inactivity. During sleep, the brain carries out functions that support memory, attention, and emotional regulation. Research has found that sleep after learning can help people retain information more effectively.","The amount of sleep people need varies with age and individual circumstances. Adults commonly need around seven to nine hours each night, although this is a guideline rather than a rule that fits everyone. Consistent sleep and wake times can help regulate the body's internal clock.","Modern habits can interfere with sleep. Bright light late in the evening may delay the release of melatonin, a hormone involved in sleep timing. Caffeine can also affect sleep, particularly when consumed later in the day."],qs:[
{type:"Multiple choice",q:"Which process is supported by sleep after learning?",opts:["Forgetting new information","Retaining information","Increasing caffeine levels","Reducing attention"],a:1,why:"The passage links sleep after learning with retaining information.",ev:"“help people retain information more effectively.”"},
{type:"Short answer",q:"Name the hormone involved in sleep timing.",a:["melatonin"],why:"The passage names melatonin as a hormone involved in sleep timing.",ev:"“melatonin, a hormone involved in sleep timing.”"},
{type:"True / False / Not Given",q:"Every adult needs exactly eight hours of sleep.",opts:["TRUE","FALSE","NOT GIVEN"],a:1,why:"Needs vary and the passage gives a general range of around seven to nine hours.",ev:"“varies with age and individual circumstances.”"}]},
{id:"wildlife",level:3,zone:"Inference Island",icon:"🏝️",title:"The Return of City Wildlife",intro:"Animals adapt to living alongside people",paras:["As cities expand, some species have learned to exploit opportunities created by human activity. Foxes, peregrine falcons, and several types of bat have been observed in urban areas. Buildings can provide nesting sites, while parks and gardens offer food and shelter.","Urban life also creates challenges. Traffic, artificial lighting, and noise can affect animal behaviour. Some species adjust their activity to quieter hours, while others avoid heavily developed areas. The ability to adapt differs considerably between species and even between individual animals.","Wildlife experts caution against assuming every urban animal is thriving. A species may be visible in a city while still facing declining numbers elsewhere. Careful monitoring is needed to understand whether more sightings reflect population growth or simply a change in where animals are observed."],qs:[
{type:"Yes / No / Not Given",q:"The writer believes every animal species benefits from urban expansion.",opts:["YES","NO","NOT GIVEN"],a:1,why:"The writer describes challenges and warns against assuming all urban animals are thriving.",ev:"“caution against assuming every urban animal is thriving.”"},
{type:"Multiple choice",q:"Why might more sightings not prove a population has grown?",opts:["All animals leave cities at night.","Animals cannot live in parks.","Animals may be observed in different places.","Experts do not study wildlife."],a:2,why:"The passage distinguishes population growth from changes in where animals are observed.",ev:"“a change in where animals are observed.”"},
{type:"True / False / Not Given",q:"Peregrine falcons only nest on buildings over ten storeys high.",opts:["TRUE","FALSE","NOT GIVEN"],a:2,why:"Buildings are mentioned as nesting sites, but no height requirement is given.",ev:"No building height is specified."}]},
{id:"repair",level:4,zone:"Paragraph Citadel",icon:"🏰",title:"Repair, Reuse, Rethink",intro:"The growing interest in repairing everyday products",paras:["For much of the twentieth century, many consumer goods were designed around relatively short replacement cycles. Recently, repair cafés, online tutorials, and community workshops have encouraged people to extend the useful lives of everyday objects. The movement has environmental and social motivations.","Repairing an item can reduce demand for raw materials and prevent usable products becoming waste. It can also help people develop practical skills and share knowledge across generations. Yet repair is not always the cheapest option: spare parts may be unavailable, devices can be difficult to open, and professional labour may cost more than replacement.","Some manufacturers have made parts and instructions more accessible, while others argue that safety, quality control, and intellectual property make unrestricted repair complicated. Policy makers are examining rules intended to improve access to repairs. Long-term effects will depend partly on whether products are designed to be repairable from the outset."],qs:[
{type:"Matching information",q:"Which paragraph mentions knowledge shared between generations?",opts:["Paragraph A","Paragraph B","Paragraph C"],a:1,why:"Paragraph B says repair can help people share knowledge across generations.",ev:"“share knowledge across generations.”"},
{type:"Multiple choice",q:"What condition could help repair become more common in the long term?",opts:["All goods must be replaced annually.","Products should be designed to be repairable.","Online tutorials should be banned.","Professional repair must be free."],a:1,why:"The final sentence highlights designing products to be repairable from the outset.",ev:"“designed to be repairable from the outset.”"},
{type:"True / False / Not Given",q:"Every manufacturer provides free spare parts for all products.",opts:["TRUE","FALSE","NOT GIVEN"],a:1,why:"The passage says some manufacturers improve access to parts, not that every manufacturer gives them away for free.",ev:"“Some manufacturers have made parts and instructions more accessible...”"}]},
{id:"transport",level:5,zone:"IELTS Reading Arena",icon:"🏆",title:"Public Transport and the Modern City",intro:"How transport systems shape urban life",paras:["Public transport is often presented as a solution to congestion, but its effectiveness depends on more than the number of buses or trains. Routes must connect homes with workplaces, schools, and essential services. If transfers are difficult or services unreliable, commuters may continue to prefer private vehicles.","Investment in transport can influence urban development. Stations often attract shops and housing, creating areas where daily needs can be met within a shorter distance. This may reduce car dependence, although it can also raise property values and make some neighbourhoods less affordable.","Technology has introduced new tools for planning networks. Real-time arrival information can reduce uncertainty, while integrated payment systems make transfers easier. However, digital services are not equally accessible to everyone. Planners must retain alternatives for passengers who lack smartphones, bank cards, or reliable internet access.","Transport policy balances competing priorities. A successful system needs dependable services, sensible land-use planning, affordability, and access for a wide range of passengers. No single technology or infrastructure project can solve every urban transport problem."],qs:[
{type:"Multiple choice",q:"Why might commuters continue using private vehicles?",opts:["Public transport is always more expensive.","Routes or services may not meet their needs reliably.","Cities have stopped building roads.","Buses cannot carry commuters."],a:1,why:"Difficult transfers and unreliable services may lead commuters to prefer private vehicles.",ev:"“If transfers are difficult or services unreliable...”"},
{type:"Yes / No / Not Given",q:"The writer argues that digital services should replace all traditional options.",opts:["YES","NO","NOT GIVEN"],a:1,why:"The writer says planners must retain alternatives for people without digital access.",ev:"“Planners must retain alternatives for passengers...”"},
{type:"Sentence completion",q:"Integrated payment systems can make transport ______ easier.",a:["transfers"],why:"The passage directly states that integrated payment systems make transfers easier.",ev:"“integrated payment systems make transfers easier.”"}]}
];
const levelInfo=[
["Vocabulary Village","🌱","Build vocabulary and spot paraphrases.","Vocabulary · Main ideas",0],
["Scanning Station","🔎","Find specific facts quickly and accurately.","Scanning · Short answers",2],
["Inference Island","🏝️","Separate facts from assumptions.","T/F/NG · Y/N/NG",3],
["Paragraph Citadel","🏰","Connect claims and supporting details.","Matching · Completion",4],
["IELTS Reading Arena","🏆","Put your skills to work in mixed practice.","Mixed questions · Timing",5]];
const blank={xp:0,answered:0,correct:0,completed:[],mistakes:[],visited:[],streak:0,lastDay:"",history:[]};
let state;try{state={...blank,...JSON.parse(localStorage.getItem("ieltsQuestRR")||"{}")}}catch(e){state={...blank}}
let game=null,timerId=null,toastId;
const $=id=>document.getElementById(id);
const norm=s=>String(s??"").trim().toLowerCase().replace(/[.,!?;:'"()]/g,"").replace(/\s+/g," ");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const acc=()=>state.answered?Math.round(state.correct/state.answered*100):null;
function save(){try{localStorage.setItem("ieltsQuestRR",JSON.stringify(state))}catch(e){}}
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");clearTimeout(toastId);toastId=setTimeout(()=>$("toast").classList.remove("show"),2200)}
function screen(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
function renderHome(){
 $("xpTop").textContent=state.xp;$("streakTop").textContent=state.streak;$("levelBadge").textContent=`Level ${Math.min(5,Math.floor(state.xp/100)+1)} · ${["Explorer","Finder","Detective","Scholar","Champion"][Math.min(4,Math.floor(state.xp/100))]}`;
 $("progressLabel").textContent=`${state.answered} questions answered`;$("accuracyLabel").textContent=`Accuracy: ${acc()===null?"—":acc()+"%"}`;$("xpBar").style.width=(state.xp%100)+"%";
 $("answered").textContent=state.answered;$("correct").textContent=state.correct;$("missions").textContent=state.completed.length;$("mistakes").textContent=state.mistakes.length;
 $("levels").innerHTML=levelInfo.map((l,i)=>`<button class="level" data-level="${i}"><span class="num">LEVEL 0${i+1}</span><span class="emoji">${l[1]}</span><h3>${l[0]}</h3><p>${l[2]}</p><small>${state.completed.includes(passages[l[4]].id)?"✓ Completed · Play again →":l[3]+" · Start →"}</small></button>`).join("");
 document.querySelectorAll("[data-level]").forEach(b=>b.onclick=()=>start([levelInfo[+b.dataset.level][4]],"mission",levelInfo[+b.dataset.level][0]));
}
function start(indices,mode,title){
 let qs=[];indices.forEach(pi=>passages[pi].qs.forEach((q,qi)=>qs.push({q,p:passages[pi],qi,pi})));
 game={qs,answers:Array(qs.length).fill(null),checked:Array(qs.length).fill(false),cur:0,start:Date.now(),mode,title,limit:mode==="mock"?2400:mode==="daily"?300:null};
 const p=passages[indices[0]];state.visited=[...new Set([...state.visited,p.level])];save();
 $("mode").textContent=mode==="mock"?"MIXED PRACTICE":mode==="daily"?"DAILY CHALLENGE":"READING MISSION";$("timer").textContent=game.limit?fmt(game.limit):"Untimed";
 renderPassage(p);renderQ();screen("practiceScreen");if(game.limit)timerId=setInterval(tick,1000);
}
function renderPassage(p){$("passageTitle").textContent=p.title;$("passageIntro").textContent=p.intro;$("passageText").innerHTML=p.paras.map((x,i)=>`<p><b>${String.fromCharCode(65+i)}.</b> ${esc(x)}</p>`).join("");}
function now(){return game.qs[game.cur]}
function renderQ(){
 let item=now(),q=item.q,i=game.cur,answered=game.checked[i];$("count").textContent=`QUESTION ${i+1} OF ${game.qs.length}`;$("type").textContent=q.type.toUpperCase();$("qBar").style.width=((i+1)/game.qs.length*100)+"%";$("question").textContent=q.q;
 $("answers").innerHTML="";
 if(q.opts){q.opts.forEach((v,j)=>{let d=document.createElement("div");d.className="answer"+(game.answers[i]===j?" selected":"");if(answered&&j===q.a)d.classList.add("good");else if(answered&&game.answers[i]===j)d.classList.add("bad");d.innerHTML=`<span class="letter">${String.fromCharCode(65+j)}</span><span>${esc(v)}</span>`;d.onclick=()=>{if(!answered){game.answers[i]=j;renderQ()}};$("answers").appendChild(d)})}
 else{let inp=document.createElement("input");inp.className="text-answer";inp.placeholder="Type your answer here";inp.value=game.answers[i]||"";inp.disabled=answered;inp.oninput=()=>game.answers[i]=inp.value;inp.onkeydown=e=>{if(e.key==="Enter"&&!game.checked[i])check()};$("answers").appendChild(inp)}
 $("feedback").className="feedback hidden";$("check").classList.toggle("hidden",answered);$("next").classList.toggle("hidden",!answered);$("next").textContent=i===game.qs.length-1?"Finish →":"Next →";$("prev").disabled=i===0;
 $("dots").innerHTML=game.qs.map((x,j)=>`<button class="dot-btn ${j===i?"current":""} ${game.checked[j]?"done":""}" data-q="${j}">${j+1}</button>`).join("");document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{game.cur=+b.dataset.q;renderQ()});
 if(answered)feedback();
}
function isRight(q,a){if(a===null||String(a).trim()==="")return false;if(q.opts)return +a===q.a;return (Array.isArray(q.a)?q.a:[q.a]).some(x=>norm(x)===norm(a))}
function feedback(){let q=now().q,ok=isRight(q,game.answers[game.cur]),right=q.opts?q.opts[q.a]:(Array.isArray(q.a)?q.a[0]:q.a);if(q.opts&&q.type==="Multiple choice")right=String.fromCharCode(65+q.a)+". "+right;$("feedback").className="feedback "+(ok?"correct":"incorrect");$("feedback").innerHTML=`<b>${ok?"✓ Correct!":"✦ Learn from this"}</b><p>${ok?"Well done.":"Correct answer: "+esc(right)}</p><p>${esc(q.why)}</p><p><b>Evidence:</b> ${esc(q.ev)}</p>`}
function check(){let i=game.cur,q=now().q,a=game.answers[i];if(a===null||String(a).trim()===""){toast("Choose or enter an answer first.");return}game.checked[i]=true;let ok=isRight(q,a);state.answered++;if(ok){state.correct++;state.xp+=10}else{let key=now().p.id+"-"+now().qi;if(!state.mistakes.some(m=>m.key===key))state.mistakes.unshift({key,q:q.q,type:q.type,answer:q.opts?q.opts[q.a]:(Array.isArray(q.a)?q.a[0]:q.a),why:q.why,ev:q.ev})}const d=new Date().toISOString().slice(0,10);if(state.lastDay!==d){let y=new Date();y.setDate(y.getDate()-1);state.streak=state.lastDay===y.toISOString().slice(0,10)?state.streak+1:1;state.lastDay=d}save();renderQ();renderHome();toast(ok?"+10 XP — great work!":"Saved to your mistake notebook")}
function next(){if(game.cur<game.qs.length-1){game.cur++;renderPassage(now().p);renderQ()}else finish()}
function fmt(s){return Math.floor(Math.max(0,s)/60)+":"+String(Math.max(0,s)%60).padStart(2,"0")}
function tick(){if(!game||!game.limit)return;let left=game.limit-Math.floor((Date.now()-game.start)/1000);$("timer").textContent=fmt(left);if(left<=0){clearInterval(timerId);game.limit=null;finish()}}
function finish(){clearInterval(timerId);let n=game.qs.length,c=game.qs.reduce((sum,x,i)=>sum+(isRight(x.q,game.answers[i])?1:0),0),xp=c*10;let ids=[...new Set(game.qs.map(x=>x.p.id))];ids.forEach(id=>{if(!state.completed.includes(id)&&game.qs.filter(x=>x.p.id===id).every(x=>game.checked[game.qs.indexOf(x)]))state.completed.push(id)});state.history.unshift({date:new Date().toISOString().slice(0,10),c,n});save();
 $("resultTitle").textContent=c===n?"Perfect reading!":c>=Math.ceil(n*.6)?"Mission accomplished!":"Keep growing!";$("resultSub").textContent="Review your answers and use the explanations to improve.";$("score").textContent=`${c}/${n}`;$("resultAcc").textContent=Math.round(c/n*100)+"%";$("resultXP").textContent="+"+xp;$("resultTime").textContent=fmt(Math.floor((Date.now()-game.start)/1000));$("resultTotal").textContent=n;
 $("reviewList").innerHTML=game.qs.map((it,i)=>{let q=it.q,a=q.opts?q.opts[q.a]:(Array.isArray(q.a)?q.a[0]:q.a);return `<div class="review-item"><b>${isRight(q,game.answers[i])?"✓":"✦"} ${i+1}. ${esc(q.q)}</b><p><b>Correct answer:</b> ${esc(a)}</p><p>${esc(q.why)}</p><p><b>Evidence:</b> ${esc(q.ev)}</p></div>`}).join("");$("reviewList").classList.add("hidden");$("review").textContent="Review answers";screen("resultScreen");renderHome()}
function openNotebook(){let list=$("mistakeList");if(!state.mistakes.length)list.innerHTML='<div class="panel"><h2>🌟 No mistakes saved yet</h2><p class="muted">When you miss a question, it will appear here with its answer and explanation.</p></div>';else list.innerHTML=state.mistakes.map((m,i)=>`<article class="mistake"><span class="badge">${esc(m.type)}</span><h3>${esc(m.q)}</h3><p><b>Correct answer:</b> ${esc(m.answer)}</p><p>${esc(m.why)}</p><p><b>Evidence:</b> ${esc(m.ev)}</p><button class="ghost" data-remove="${i}">Mark reviewed</button></article>`).join("");document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{state.mistakes.splice(+b.dataset.remove,1);save();openNotebook();renderHome()});screen("notebookScreen")}
function openProgress(){let ids=["pXP","pAnswers","pAcc","pDone"];[state.xp,state.answered,acc()===null?"—":acc()+"%",state.completed.length].forEach((v,i)=>$(ids[i]).textContent=v);let a=[["🌱","First steps","Answer your first question",state.answered>=1],["🎯","Sharp focus","Reach 80% accuracy (5 answers)",state.answered>=5&&acc()>=80],["⭐","XP collector","Earn 100 XP",state.xp>=100],["📘","Bookworm","Complete 3 passages",state.completed.length>=3],["🔥","Daily habit","Practise on 3 days",state.streak>=3],["🏆","Realm explorer","Explore all 5 levels",state.visited.length>=5]];$("achievements").innerHTML=a.map(x=>`<div class="achievement ${x[3]?"earned":""}"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join("");screen("progressScreen")}
$("start").onclick=()=>start([0],"mission","Vocabulary Village");$("mock").onclick=()=>start([0,1,2,3,4,5],"mock","Mixed practice");$("daily").onclick=()=>start([Math.floor(Math.random()*passages.length)],"daily","Daily challenge");$("notebook").onclick=openNotebook;$("progress").onclick=openProgress;$("back").onclick=()=>{clearInterval(timerId);screen("homeScreen");renderHome()};$("home").onclick=e=>{e.preventDefault();clearInterval(timerId);screen("homeScreen");renderHome()};document.querySelectorAll(".backHome").forEach(b=>b.onclick=()=>screen("homeScreen"));$("check").onclick=check;$("next").onclick=next;$("prev").onclick=()=>{if(game&&game.cur>0){game.cur--;renderPassage(now().p);renderQ()}};$("review").onclick=()=>{$("reviewList").classList.toggle("hidden");$("review").textContent=$("reviewList").classList.contains("hidden")?"Review answers":"Hide review"};$("resultHome").onclick=()=>{screen("homeScreen");renderHome()};$("reset").onclick=()=>{if(confirm("Reset all IELTS Quest progress stored in this browser?")){state={...blank};save();renderHome();openProgress();toast("Progress reset.")}};renderHome();
